name: tekartik_fs_browser
description: Fs browser
version: 0.3.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=3.4.0-0 <4.0.0'

dependencies:
  path: '>=1.6.1'
  fs_shim: '>=0.11.0+3'
  idb_shim:

dev_dependencies:
  lints: '>=1.0.1'
  test: ">=1.0.0"
  build_runner: ">=0.8.8"
  build_web_compilers: ">=0.1.3"
  tekartik_fs_test:
    git:
      url: https://github.com/tekartik/fs_shim.dart
      path: fs_test
      ref: dart3a
    version: '>=0.1.0'
  build_test: '>=0.10.2'
  process_run: '>=0.10.0+1'
  tekartik_platform_browser:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform_browser
      ref: dart3a
    version: '>=0.2.0'

dependency_overrides:
  fs_shim:
    path: ../fs
  tekartik_fs_test:
    path: ../fs_test

# node_io:
#   git:
#      url: https://github.com/tekartik/node-interop
#      path: node_io
#  node_io:
#    path: /media/ssd/devx/git/github.com/tekartik/node-interop/node_io
#  tekartik_platform:
#    path: /media/ssd/devx/git/github.com/tekartik/platform.dart/platform
#  tekartik_platform_node:
#    path: /media/ssd/devx/git/github.com/tekartik/platform.dart/platform_node
