language: dart

sudo: required
addons:
  chrome: stable

before_install:
- nvm install node
- node --version

jobs:
  include:
    - stage: stable
      script: ./tool/travis.sh
      dart: stable
    - stage: dev
      script: ./tool/travis_dev.sh
      dart: dev

stages:
  - stable
  - dev

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master
    - dart2

cache:
  directories:
    - $HOME/.pub-cache