name: tekartik_fs_shim_repo
description: fs shim repo (tools)
version: 0.1.0
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.2.2-dev <3.0.0'

dev_dependencies:
  test: ">=0.12.34"
  dev_test: any
  grinder: any
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
    version: '>=0.3.4'
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'
  process_run: '>=0.10.0'