name: fs_shim
description: A portable file system implementation working on io, browser and memory (through idb_shim)
version: 0.6.2
author: Tekartik <alex@tekartik.com>
homepage: https://github.com/tekartik/fs_shim.dart

environment:
  sdk: '>=1.17.1 <2.0.0'

dependencies:
  idb_shim: any
  path: any

test_dependencies:
  - platform_context
  - idb_shim

dev_dependencies:
  test: any
  dev_test: any
  browser: any
  platform_context:
    git: https://github.com/alextekartik/platform_context.dart
