name: tekartik_fs_test
description: Fs test
version: 0.0.1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:
  fs_shim: '>=0.9.0-dev.1'
  path: '>=1.6.1'
  tekartik_platform:
    git:
      url: git://github.com/tekartik/platform.dart
      path: platform
      ref: dart2
  tekartik_common_utils:
    git: git://github.com/tekartik/common_utils.dart
  test: ">=1.2.0"
  dev_test: any
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'

dev_dependencies:
  tekartik_platform_io:
    git:
      url: git://github.com/tekartik/platform.dart
      path: platform_io
      ref: dart2
  build_web_compilers: '>=0.4.0'

dependency_overrides:
  fs_shim:
    path: ../fs
  idb_shim:
    path: ../../idb_shim.dart