name: tekartik_fs_test
description: Fs test
version: 0.0.1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:
  fs_shim: any
  tekartik_platform:
    git:
      url: git://github.com/tekartik/platform.dart
      path: platform
  tekartik_common_utils:
    git: git://github.com/tekartik/common_utils.dart
  test: ">=0.12.37"
  dev_test: any

dependency_overrides:
  fs_shim:
    path: ../fs
  tekartik_platform:
    path: /media/ssd/devx/git/github.com/tekartik/platform.dart/platform