name: tekartik_fs_test
description: Fs test
version: 0.4.3
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=3.4.0-0 <4.0.0'

dependencies:
  fs_shim: '>=2.1.0-2'
  path: '>=1.6.1'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.7'
  test: ">=1.2.0"

dev_dependencies:
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
  lints: '>=1.0.1'
  process_run: '>=0.10.3'
  tekartik_platform_io:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform_io
      ref: dart3a
  build_web_compilers: '>=0.4.0'

dependency_overrides:
  fs_shim:
    path: ../fs
#  idb_shim:
#    path: ../../idb_shim.dart
