name: tekartik_fs_test
description: Fs test
version: 0.0.1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:
  fs_shim: any
  platform_context:
    git: https://github.com/tekartik/platform_context.dart
  test: ">=0.12.37"
  dev_test: any

dependency_overrides:
  fs_shim:
    path: ../fs