name: fs_shim
description: A portable file system implementation working on io, browser and memory (through idb_shim)
version: 2.1.0-6
homepage: https://github.com/tekartik/fs_shim.dart/tree/master/fs

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  idb_shim: '>=2.2.0+8 <4.0.0'
  sembast: '>=3.0.0 <5.0.0'
  synchronized: '>=3.0.0 <5.0.0'
  path: '>=1.8.0 <3.0.0'
  meta: '>=1.3.0 <3.0.0'

dev_dependencies:
  lints: '>=1.0.1'
  process_run: '>=0.12.0'
  test: '>=1.16.2'
  dev_test: '>=0.15.0'
  build_runner: '>=1.11.3'
  build_test: '>=1.3.7'
  build_web_compilers: '>=2.16.4'
  yaml: '>=3.0.0'
  pub_semver: '>=2.0.0'
