name: fs_shim
description: A portable file system implementation working on io, browser and memory (through idb_shim)
version: 0.11.0+3
author: Tekartik <alex@tekartik.com>
homepage: https://github.com/tekartik/fs_shim.dart

environment:
  sdk: '>=2.4.0-dev <3.0.0'

dependencies:
  idb_shim: '>=1.10.0-dev <3.0.0'
  path: '>=1.5.1 <3.0.0'

dev_dependencies:
  pedantic: '>=1.4.0'
  process_run: '>=0.10.0+1'
  test: '>=1.2.0'
  dev_test: '>=0.13.1'
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'

