name: fs_shim
description: A portable file system implementation working on io, browser and memory (through idb_shim)
version: 2.0.0-nullsafety.1
homepage: https://github.com/tekartik/fs_shim.dart/tree/master/fs

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  idb_shim: '>=2.0.0-nullsafety.5 <4.0.0'
  sembast: '>=3.0.0-nullsafety.3 <4.0.0'
  path: '>=1.8.0-nullsafety.3 <3.0.0'
  meta: '>=1.3.0-nullsafety.6 <3.0.0'

dev_dependencies:
  pedantic: '>=1.8.0'
  process_run: '>=0.10.9+2'
  test: '>=1.16.0-nullsafety.12'
  dev_test: '>=0.13.1'
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'
  io:
  yaml: '>=3.0.0-nullsafety.0'
  pub_semver:

