name: fs_shim
description: A portable file system implementation working on io, browser and memory (through idb_shim)
version: 0.9.0-dev.1
author: Tekartik <alex@tekartik.com>
homepage: https://github.com/tekartik/fs_shim.dart

environment:
  sdk: '>=2.0.0-dev.63 <2.0.0'

dependencies:
  idb_shim: '>=1.6.0-dev.2'
  path: '>=1.6.1'
  dart2_constant: '>=1.0.1'

dev_dependencies:
  test: '>=1.2.0'
  dev_test: '0.12.0-dev.1'
  browser: any
  platform_context:
    git: https://github.com/tekartik/platform_context.dart
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart
    version: '>=0.1.3'
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'

# dependency_overrides:
#  sembast:
#    path: ../sembast.dart
#  idb_shim:
#    path: ../idb_shim.dart
