name: tekartik_fs_node
description: Fs node
version: 0.0.1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:
  fs_shim: any
  node_interop: ">=1.0.0-dev.7"
  # node_io: '>=1.0.0-dev.5'
  node_io:
    git:
      url: git://github.com/tekartik/node-interop
      path: node_io

dev_dependencies:
  test: ">=0.12.37"
  dev_test: any
  build_runner: ">=0.8.8"
  build_node_compilers: ">=0.1.3"
  tekartik_fs_test:
    path: ../fs_test
  build_test: '>=0.10.2'
  tekartik_platform:
    git:
      url: git://github.com/tekartik/platform.dart
      path: platform
  tekartik_platform_node:
    git:
      url: git://github.com/tekartik/platform.dart
      path: platform_node

dependency_overrides:
  fs_shim:
    path: ../fs
#  node_io:
#    path: /media/ssd/devx/git/github.com/tekartik/node-interop/node_io
#  tekartik_platform:
#    path: /media/ssd/devx/git/github.com/tekartik/platform.dart/platform
#  tekartik_platform_node:
#    path: /media/ssd/devx/git/github.com/tekartik/platform.dart/platform_node