name: tekartik_fs_io
description: Fs for dart io
version: 0.4.1
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.18.0-0 <3.0.0'

dependencies:
  path: '>=1.6.1'
  fs_shim: '>=0.11.0+3'

dev_dependencies:
  lints: '>=1.0.1'
  test: ">=1.0.0"
  dev_test: any
  build_runner: ">=0.8.8"
  tekartik_fs_test:
    git:
      url: https://github.com/tekartik/fs_shim.dart
      path: fs_test
      ref: dart2_3
    version: '>=0.1.0'
  build_test: '>=0.10.2'
  process_run: '>=0.10.0+1'
  tekartik_platform_io:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform_io
      ref: dart2_3
    version: '>=0.2.0'

dependency_overrides:
  fs_shim:
    path: ../fs
  tekartik_fs_test:
    path: ../fs_test

# node_io:
#   git:
#      url: https://github.com/tekartik/node-interop
#      path: node_io
#  node_io:
#    path: /media/ssd/devx/git/github.com/tekartik/node-interop/node_io
#  tekartik_platform:
#    path: /media/ssd/devx/git/github.com/tekartik/platform.dart/platform
#  tekartik_platform_node:
#    path: /media/ssd/devx/git/github.com/tekartik/platform.dart/platform_node